server:
  port: 8080
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/coffeeshop?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cl.jdbc.Driver
      username: root
      password: tim530216378